force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Thankyou_Page__c/Thankyou_Page__c.object-meta.xml
<CustomObject>
    <label>Thankyou Page</label>
    <nameField>
        <label>Thankyou Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thankyou Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Thankyou_Page__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Thankyou Pages</relationshipLabel>
    <relationshipName>Thankyou_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Thankyou_Page__c/fields/Thank_you_URL__c.field-meta.xml
<CustomField>
    <fullName>Thank_you_URL__c</fullName>
    <label>Thank you URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Thankyou_Page__c/fields/Thankyou_Page_Type__c.field-meta.xml
<CustomField>
    <fullName>Thankyou_Page_Type__c</fullName>
    <label>Thankyou Page Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Show Text</fullName>
            </value>
            <value>
                <fullName>Redirect to a webpage</fullName>
            </value>
            <value>
                <fullName>Show text, then redirect to web page</fullName>
            </value>
            <value>
                <fullName>Show report of User data</fullName>
            </value>
            <value>
                <fullName>Show HTML block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Thankyou_Page__c/fields/Thankyou_Text__c.field-meta.xml
<CustomField>
    <fullName>Thankyou_Text__c</fullName>
    <label>Thankyou Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/qfthankyou.cls
public with sharing class qfthankyou {
   @AuraEnabled
   public static string insertrecord(String picklist, String text,String richtext, String formId, String url){
    try {
        if(String.isNotBlank(text)){
        Thankyou_Page__c insertrecord = new Thankyou_Page__c( Form__c = formId, Thank_you_URL__c = url, Thankyou_Text__c = text, Thankyou_Page_Type__c = picklist, Name = 'Thank you' ); 
        Database.upsert(insertrecord);
        }
        else if(String.isNotBlank(richtext)){
        Thankyou_Page__c insertrecord = new Thankyou_Page__c( Form__c = formId, Thank_you_URL__c = url, Thankyou_Text__c = richtext, Thankyou_Page_Type__c = picklist, Name = 'Thank you' );
        Database.upsert(insertrecord);
        }
        else{
            Thankyou_Page__c insertrecord = new Thankyou_Page__c( Form__c = formId, Thank_you_URL__c = url, Thankyou_Page_Type__c = picklist, Name = 'Thank you' );
            Database.upsert(insertrecord); 
        }
        
        return null;
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }
}