force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/All_Field_Focus__c.field-meta.xml
<CustomField>
    <fullName>All_Field_Focus__c</fullName>
    <label>All_Field_Focus</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/All_Field_Hover__c.field-meta.xml
<CustomField>
    <fullName>All_Field_Hover__c</fullName>
    <label>All_Field_Hover</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/All_Field_Styling__c.field-meta.xml
<CustomField>
    <fullName>All_Field_Styling__c</fullName>
    <label>All_Field_Styling</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Button_CSS__c.field-meta.xml
<CustomField>
    <fullName>Button_CSS__c</fullName>
    <label>Button_CSS</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Button_Position__c.field-meta.xml
<CustomField>
    <fullName>Button_Position__c</fullName>
    <label>Button_Position</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Captcha_Type__c.field-meta.xml
<CustomField>
    <fullName>Captcha_Type__c</fullName>
    <label>Captcha_Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal_Captcha</fullName>
                <label>Normal Captcha</label>
            </value>
            <value>
                <fullName>Normal_Captcha_In_Popup</fullName>
                <label>Normal Captcha In Popup</label>
            </value>
            <value>
                <fullName>Maths_Captcha</fullName>
                <label>Maths Captcha</label>
            </value>
            <value>
                <fullName>Slider_Captcha</fullName>
                <label>Slider Captcha</label>
            </value>
            <value>
                <fullName>Image_Captcha</fullName>
                <label>Image Captcha</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/fields/Form_Description__c.field-meta.xml
<CustomField>
    <fullName>Form_Description__c</fullName>
    <label>Form_Description</label>
    <length>32786</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Form_Styling__c.field-meta.xml
<CustomField>
    <fullName>Form_Styling__c</fullName>
    <label>Form_Styling</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/FormBgID__c.field-meta.xml
<CustomField>
    <fullName>FormBgID__c</fullName>
    <label>FormBgID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Label_CSS__c.field-meta.xml
<CustomField>
    <fullName>Label_CSS__c</fullName>
    <label>Label_CSS</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Mapped_Objects__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Objects__c</fullName>
    <label>Mapped_Objects</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Page_CSS__c.field-meta.xml
<CustomField>
    <fullName>Page_CSS__c</fullName>
    <label>Page_CSS</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/PageBgID__c.field-meta.xml
<CustomField>
    <fullName>PageBgID__c</fullName>
    <label>PageBgID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Progress_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Progress_Indicator__c</fullName>
    <label>Progress_Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Page_Count</fullName>
                <label>Page Count</label>
            </value>
            <value>
                <fullName>Progress_Bar</fullName>
                <label>Progress Bar</label>
            </value>
            <value>
                <fullName>Standard_Steps</fullName>
                <label>Standard Steps</label>
            </value>
            <value>
                <fullName>Custom_Steps</fullName>
                <label>Custom Steps</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Total_Submissions__c.field-meta.xml
<CustomField>
    <fullName>Total_Submissions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total_Submissions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Fields__c/Form_Fields__c.object-meta.xml
<CustomObject>
    <label>Form Fields</label>
    <nameField>
        <label>Form_Fields Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form_Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Fields__c/fields/Field_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Field_Mapping__c</fullName>
    <label>Field_Mapping</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Fields__c/fields/Field_Order__c.field-meta.xml
<CustomField>
    <fullName>Field_Order__c</fullName>
    <label>Field_Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Fields__c/fields/Field_Properties__c.field-meta.xml
<CustomField>
    <fullName>Field_Properties__c</fullName>
    <label>Field_Properties</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Fields__c/fields/Field_Styling__c.field-meta.xml
<CustomField>
    <fullName>Field_Styling__c</fullName>
    <label>Field_Styling</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Fields__c/fields/Field_Validations__c.field-meta.xml
<CustomField>
    <fullName>Field_Validations__c</fullName>
    <label>Field Validations</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Fields__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipName>Form_Fields</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Fields__c/fields/Form_Page__c.field-meta.xml
<CustomField>
    <fullName>Form_Page__c</fullName>
    <label>Form Page</label>
    <referenceTo>Form_Page__c</referenceTo>
    <relationshipLabel>Form_Fields</relationshipLabel>
    <relationshipName>Form_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Fields__c/fields/Mapped_Obj__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Obj__c</fullName>
    <description>This field store Mapped Object field</description>
    <label>Mapped_Obj</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Page__c/Form_Page__c.object-meta.xml
<CustomObject>
    <label>Form Page</label>
    <nameField>
        <label>Form_Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form_Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Page__c/fields/AllField_Styling__c.field-meta.xml
<CustomField>
    <fullName>AllField_Styling__c</fullName>
    <label>AllField_Styling</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Page__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form_Pages</relationshipLabel>
    <relationshipName>Form_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Page__c/fields/Page_Number__c.field-meta.xml
<CustomField>
    <fullName>Page_Number__c</fullName>
    <label>Page_Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Page__c/fields/Page_Styling__c.field-meta.xml
<CustomField>
    <fullName>Page_Styling__c</fullName>
    <label>Page_Styling</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Thankyou_Page__c/Thankyou_Page__c.object-meta.xml
<CustomObject>
    <label>Thankyou Page</label>
    <nameField>
        <label>Thankyou Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thankyou Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Thankyou_Page__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Thankyou Pages</relationshipLabel>
    <relationshipName>Thankyou_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Thankyou_Page__c/fields/See_Response__c.field-meta.xml
<CustomField>
    <fullName>See_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>See Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Thankyou_Page__c/fields/Thank_you_URL__c.field-meta.xml
<CustomField>
    <fullName>Thank_you_URL__c</fullName>
    <label>Thank you URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Thankyou_Page__c/fields/ThankYou_Label__c.field-meta.xml
<CustomField>
    <fullName>ThankYou_Label__c</fullName>
    <label>ThankYou_Label</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Thankyou_Page__c/fields/Thankyou_Page_Type__c.field-meta.xml
<CustomField>
    <fullName>Thankyou_Page_Type__c</fullName>
    <label>Thankyou Page Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Show Text</fullName>
            </value>
            <value>
                <fullName>Redirect to a webpage</fullName>
            </value>
            <value>
                <fullName>Show text, then redirect to web page</fullName>
            </value>
            <value>
                <fullName>Show report of User data</fullName>
            </value>
            <value>
                <fullName>Show HTML block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Thankyou_Page__c/fields/Thankyou_Text__c.field-meta.xml
<CustomField>
    <fullName>Thankyou_Text__c</fullName>
    <label>Thankyou Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QuickFormHome.cls
//  ===================================
// # MV Clouds Private Limited
// # Author: Nimit Shah
// # Create Date: 09/01/2023
// # Description: Used for Edit, Delete, Read or Create New Form
// # Change Version History
// # Version No.     Author          Date            Change Description            Jira Ticket
// #    1.           Nimit         09/01/2023           Home Page UI 			 QUIC-37, QUIC-36
// =================================== 

//   Edited as per sheet(qf_home.cls - 1)
public with sharing class QuickFormHome {

// <!-- ===================================
// # MV Clouds Private Limited
// # Author: Nimit Shah
// # Create Date: 09/01/2023
// # Description: Used to Read All Forms record
// =================================== -->
    @AuraEnabled
    // public static Map<Integer,List<Form__c>> getFormRecords(){
    //     try {
    //         List<Form__c> forms = [SELECT Id,Name,Total_Submissions__c, Status__c FROM Form__c];
    //         Integer count = [SELECT Count() FROM Form__c];
    //         Map<Integer,List<Form__c>> data = new Map<Integer,List<Form__c>>();
    //         data.put(count,forms);
    //         return data;
    //     } catch (Exception e) {
    //         throw new AuraHandledException(e.getMessage());
    //     }
    // }

    //   Edited as per sheet(qf_home.cls - 2 & 3)

    public static List<Form__c> getFormRecords() {
        try {
            List<Form__c> forms = [SELECT Id,Name,Total_Submissions__c, Status__c FROM Form__c];
            return forms;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    


// <!-- ===================================
// # MV Clouds Private Limited
// # Author: Nimit Shah
// # Create Date: 09/01/2023
// # Description: Used to Search Form
// =================================== -->
    @AuraEnabled
    // public static Map<Integer,List<Form__c>> searchForms(String searchkey){
    //     try {
    //         List<Form__c> forms = [SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c WHERE Name LIKE:'%'+searchkey+'%'];
    //         Integer count = [SELECT Count() FROM Form__c WHERE Name LIKE:'%'+searchkey+'%'];
    //         Map<Integer,List<Form__c>> data = new Map<Integer,List<Form__c>>();
    //         data.put(count,forms);
    //         return data;
            
    //     } catch (Exception e) {
    //         throw new AuraHandledException(e.getMessage());
    //     }
    // }

    //   Edited as per sheet(qf_home.cls - 2 & 3 & 4)

    public static List<Form__c> searchForms(String searchkey) {
        try {
          return [SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c WHERE Name LIKE:'%'+searchkey+'%'];
        } catch (Exception e) {
          throw new AuraHandledException(e.getMessage());
        }
    }
    


// <!-- ===================================
// # MV Clouds Private Limited
// # Author: Nimit Shah
// # Create Date: 09/01/2023
// # Description: Used to Change Status of form
// =================================== -->

    //   Edited as per sheet(qf_home.cls - 2 & 3 & 5)

    @AuraEnabled
    public static List<Form__c> getFormsByStatus(Id id, String searchkey){
        try {

            Form__c form = [SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c WHERE Id =: id];

            if (form.Status__c == true) {
                form.Status__c = false;
            }
            else {
                form.Status__c = true;
            }
            update form;
            
            // if(searchkey == null || searchkey == '' || searchkey == 'undefined'){
            // List<Form__c> forms = [SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c];
            // return forms;
            // }
            // else{
            // List<Form__c> forms = [SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c WHERE Name LIKE:'%'+searchkey+'%'];
            // return forms;
            // }
            String searchkeyword = '%'+searchkey+'%'; 
            String query = 'SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c';
            if (searchkey != null && searchkey != '' && searchkey != 'undefined') {
                query += ' WHERE Name LIKE :searchkeyword';
            }
            List<Form__c> forms = Database.query(query);
            return forms;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


// <!-- ===================================
// # MV Clouds Private Limited
// # Author: Nimit Shah
// # Create Date: 09/01/2023
// # Description: Used to delete form
// =================================== -->

    //   Edited as per sheet(qf_home.cls - 2 & 3 & 5)

    @AuraEnabled
    public static List<Form__c> deleteFormRecord(Id id, String searchkey){
        try {
            Form__c form = [SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c WHERE Id =: id];
            delete form;
            
            // if(searchkey == null || searchkey == '' || searchkey == 'undefined'){
            //     List<Form__c> forms = [SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c];
            //     return forms;
            //     }
            //     else{
            //     List<Form__c> forms = [SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c WHERE Name LIKE:'%'+searchkey+'%'];
            //     return forms;
            //     }
            String searchkeyword = '%'+searchkey+'%'; 
            String query = 'SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c';
            if (searchkey != null && searchkey != '' && searchkey != 'undefined') {
                query += ' WHERE Name LIKE :searchkeyword';
            }
            List<Form__c> forms = Database.query(query);
            return forms;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


// <!-- ===================================
// # MV Clouds Private Limited
// # Author: Nimit Shah
// # Create Date: 09/01/2023
// # Description: Used to Rename form
// =================================== -->

    //   Edited as per sheet(qf_home.cls - 2)

    @AuraEnabled
    public static List<Form__c> renameFormRecord(Id id, String rename, String searchkey){
        try {
            Form__c form = [SELECT Name FROM Form__c WHERE Id =: id];
            form.Name = rename;
            update form;        
            String searchkeyword = '%'+searchkey+'%'; 
            String query = 'SELECT Id, Name, Status__c, Total_Submissions__c FROM Form__c';
            if (searchkey != null && searchkey != '' && searchkey != 'undefined') {
                query += ' WHERE Name LIKE :searchkeyword';
            }
            List<Form__c> forms = Database.query(query);
            return forms;
                
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Form__c> CopyForm(Id id){
        try {
            Integer i = 0;

            Form__c selectedform = [SELECT Id, Name, All_Field_Focus__c, All_Field_Hover__c, All_Field_Styling__c, Button_CSS__c, Button_Position__c, Captcha_Type__c, Form_Description__c,
            Form_Styling__c, FormBgID__c, Label_CSS__c, Mapped_Objects__c, Page_CSS__c, PageBgID__c, Progress_Indicator__c, Status__c FROM Form__c WHERE Id =: id Limit 1];

            List<Form_Fields__c> selectedformfield = [SELECT Id, Name, 	Field_Validations__c, Field_Mapping__c, Field_Order__c, Field_Properties__c, Field_Styling__c,
            Form__c, Form_Page__c, Mapped_Obj__c FROM Form_Fields__c WHERE Form__c =: id];

            List<Form_Page__c> selectedformpage = [SELECT Id, Name, AllField_Styling__c, Form__c, Page_Number__c, Page_Styling__c FROM Form_Page__c WHERE Form__c =: id];

            Form__c copyform = new Form__c(
                Name = selectedform.Name + ' Copy',
                All_Field_Focus__c = selectedform.All_Field_Focus__c, 
                All_Field_Hover__c = selectedform.All_Field_Hover__c,
                All_Field_Styling__c = selectedform.All_Field_Styling__c,
                Button_CSS__c = selectedform.Button_CSS__c,
                Button_Position__c = selectedform.Button_Position__c,
                Captcha_Type__c = selectedform.Captcha_Type__c,
                Form_Description__c = selectedform.Form_Description__c,
                Form_Styling__c = selectedform.Form_Styling__c,
                FormBgID__c = selectedform.FormBgID__c,
                Label_CSS__c = selectedform.Label_CSS__c,
                Mapped_Objects__c = selectedform.Mapped_Objects__c,
                Page_CSS__c = selectedform.Page_CSS__c,
                PageBgID__c = selectedform.PageBgID__c,
                Progress_Indicator__c = selectedform.Progress_Indicator__c,
                Status__c = selectedform.Status__c 
            );
            insert copyform;

            
            if([SELECT Count() FROM Thankyou_Page__c WHERE Form__c =: id ] > 0){
                Thankyou_Page__c selectedformthankyou = [SELECT Id, Name, Email_Address__c, Form__c, See_Response__c, Thank_you_URL__c, Thankyou_Page_Type__c,
                Thankyou_Text__c, ThankYou_Label__c FROM Thankyou_Page__c WHERE Form__c =: id Limit 1];

                Thankyou_Page__c copythankyoupage = new Thankyou_Page__c(
                    Name = selectedformthankyou.Name + ' Copy',
                    Email_Address__c = selectedformthankyou.Email_Address__c,
                    Form__c = copyform.Id,
                    See_Response__c = selectedformthankyou.See_Response__c,
                    Thank_you_URL__c = selectedformthankyou.Thank_you_URL__c,
                    Thankyou_Page_Type__c = selectedformthankyou.Thankyou_Page_Type__c,
                    Thankyou_Text__c = selectedformthankyou.Thankyou_Text__c,
                    ThankYou_Label__c = selectedformthankyou.ThankYou_Label__c
                );
                insert copythankyoupage;
            }

            List<Form_Page__c> copypagelist = new List<Form_Page__c>();
            for(Form_Page__c page : selectedformpage){
                Form_Page__c copypage = new Form_Page__c(
                    Name = page.Name + ' Copy',
                    AllField_Styling__c = page.AllField_Styling__c,
                    Form__c = copyform.Id,
                    Page_Number__c = page.Page_Number__c,
                    Page_Styling__c = page.Page_Styling__c
                );
                copypagelist.add(copypage);
            }
            insert copypagelist;

            List<Form_Fields__c> copyfieldlist = new List<Form_Fields__c>();
            Form_Fields__c copyfield = new Form_Fields__c();
            for(Form_Page__c pages : selectedformpage){
                for(Form_Fields__c field : selectedformfield){

                    if(pages.Id == field.Form_Page__c){

                        copyfield.Name = field.Name + ' Copy';
                        copyfield.Field_Validations__c = field.Field_Validations__c;
                        copyfield.Field_Mapping__c = field.Field_Mapping__c;
                        copyfield.Field_Order__c = field.Field_Order__c;
                        copyfield.Field_Properties__c = field.Field_Properties__c;
                        copyfield.Field_Styling__c = field.Field_Styling__c;
                        copyfield.Form__c = copyform.Id;
                        copyfield.Form_Page__c = copypagelist[i].Id;
                        copyfield.Mapped_Obj__c = field.Mapped_Obj__c;
                    }
                    i++;
                    copyfieldlist.add(copyfield);
                }
            }
            insert copyfieldlist;

            
            return  [SELECT Id,Name,Total_Submissions__c, Status__c FROM Form__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}